dist: bionic
group: travis_latest
language: python
cache: ccache

os:
- linux
# - osx
# - windows

install: 
- pip install meson==0.53.0 gcovr==4.2 ninja==1.8.2

script:
- mkdir build && cd build
- meson -Db_coverage=true ..
- ninja
- ninja test

after_success:
- ninja coverage
- curl -s https://codecov.io/bash | sed 's/-execdir $gcov_exe/-exec $gcov_exe/' | bash -s -- -g '*/example/*' -g '*/test/*'
