language: c
cache: ccache

# os:
# - linux
# - osx
# - windows

install: 
- sudo pip3 install meson
- sudo /usr/sbin/update-ccache-symlinks

script:
- meson build
- ninja -C build
- ninja -C build test

# matrix:
#   include:
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
# Uncomment this when we're ready for Mac
#     - os: osx
#       osx_image: xcode8
#       env:
#         - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build
      - ccache
      - g++-7
