dist: bionic
group: travis_latest
language: python
cache: ccache

os:
- linux
# - osx
# - windows

install: 
- pip install meson ninja

script:
- meson -Db_coverage=true build
- ninja -C build
- ninja -C build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
